### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by witlessbird** [theforeman/smart_proxy_dhcp_infoblox#12]
Not sure if this is the best way to ask questions re: implementation, let me know if something else would work better.

- Why is 'infoblox_subnets' setting necessary? Among other things it violates the semantics of dhcp module 'subnets' setting, which is a filter (and will probably be removed in future versions of smart-proxy).
- Why are all service restarts needed after record creation and removal? I assume no infoblox services are available during such a restart?
- Why is 'wapi_version' a setting -- is there any point in using older versions of the api?
- Why support 'record:host' objects? These are dns zone records and not dhcp objects... Conversely, not every record returned is a reservation, but I see no support for leases?
- Why is 'range' setting needed? Probably best to allocate all managed ips from a pool (this is what MS provider does).

Cheers,
-Dmitri

**Comment by sjoeboo** [comment]
Dmitri,

So some hopefully helpful, though I wouldn't say I'm the authoritative source on all of these: 

- infoblox_subnets: I agree, it does seem redundant. We should load subnets from infoblox, and filter with the subnets provided, if any. In my environment I also use a user in infoblox who ONLY has access to these subnets (otherwise would return a few hundred nets). 

- restarts: Yes, sadly for many (dhcp) operations, infoblox needs to restart services for changes to take affect. Typically one has a grid of infoblox systems, so the restart only affects one at a time, leaving services available while the restart propigates. It IS possible to avoid this, when setting fixedAddress records, via an Infoblox setting which allows those changes (and only those) to take place without a restart, however those fixed address records cannot be inside an existing dhcp range, otherwise a restart is still needed. 

- wapi_version: basically, the infoblox gem assumes version 1.0, and in my environment I needed v2. I didn't want to assume all environments had that/wanted to use it, hence the settings. Also incase of future upgrades (v3, etc). I figured having that being user selectable would be helpful, or at least not harmful. 

- record:host : So, these ARE dhcp objects in infoblox, but also dns ones. They are basically a one-stop-shop method of mapping a mac-address to an ip to a dns record. I personally don't use them, but others might, and one of the original contributions for this plugin used them (One could turn that on, and simply not use a DNS proxy provider and let this one take care of it...) 

- range: Basically, I didn't want to assume al environments were like mine for Infoblox. We typically either do not define a range, or define a small one, and want our fixed address changes to exist outside of those ranges. However, others may use ranges, and the API calls to find addresses/make records differ between in a range (Range) and not (Subnet).

I hope this helps, let me know if I misunderstood anything or didn't answer you questions. I'd like to avoid supporting all the options ever, but, from my limited Infoblox exposure, it seems there are a number of ways to run it, so I'd like to make it possible to make with as many of those as possible, as opposed to just a few specific setups (for example, in my environment, I don't "own" or "run" infoblox, a central team does and it supports thousands of users/systems outside my environment, so I can't really bend IT to fit my will, but rather have to go the other way around).

**Comment by Klaas-** [comment]
Hi Dmitri,
- The infoblox_subnets is a workaround because the smart proxy loads all networks on every call; if you have a lot of networks on your infoblox appliance it can take long (for me 30+ seconds with around 4k networks). I was thinking about caching them in smart proxy but this was the quickest fix I could think of :)
- service restarts are needed because dhcp records don't go live until you restart the dhcp service; if you have a grid you need to wait until every server in grid has restarted until you can be sure you're newly created vm will get a dhcp resonse; I was asking in #foreman-dev about the possibility to add a custom wait time through foreman after creating the dhcp objects; so the wait time is just a workaround until I get the time to look into doing it right through foreman
- wapi version is not strictly needed at the moment but maybe it makes sense to support different versions in future
- host objects are explained in the readme; basically they are ipam objects that can include dns and dhcp, my network team forces me to use those :)
- we don't use leases so I didn't implement it, not sure if infoblox api supports them
- range seems to be needed on big networks (/20 and bigger) but I can't say anything to that; not using those @sjoeboo @georg-rath may know more

**Comment by witlessbird** [comment]
Cheers for answers!

- infoblox_subnets: 
Looks like it's possible to apply a network address filter to only retrieve networks one is interested in, which should cut down the response time (haven't tried, based on the docs): 
```
::Infoblox::Network.all(@connection, 'network~' => '1.1.1.0/24|1.1.2.0/24')
```
- service restarts: Doesn't sound like it should be an option, as pretty much any dhcp change requires one? It might be possible to get rid of 'restart_sleep' -- there is a grid:servicerestart:status object that might help
- wapi_version: Probably should be fixed at 2.0 for the time being, as this is the version that is used in production/testing.
- record:host: ok.
- range: ok.

-d

**Comment by georg-rath** [comment]
- regarding service restart: I implemented it like this: https://github.com/IMPIMBA/smart_proxy_dhcp_infoblox/blob/internal_merge/lib/smart_proxy_dhcp_infoblox/dhcp_infoblox_main.rb#L198 . it is a bit hacky to retry, but necessary, cause if you do a restart too quick the WAPI call throws an exception. this needs a recent version of the infoblox gem (see https://github.com/govdelivery/infoblox/pull/41).
- we map foreman ranges to infoblox ranges and use those for next_free_ip functionality. the exclusion approach can kill your (our) appliance with big networks (/20). our use case is dividing a /20 into smaller ranges. implementation is here: https://github.com/IMPIMBA/smart_proxy_dhcp_infoblox/blob/internal_merge/lib/smart_proxy_dhcp_infoblox/dhcp_infoblox_main.rb#L112

Best regards,
Georg

**Comment by witlessbird** [comment]
It sounds like there are two use-cases for ranges when used for address allocation:
 - not use them at all
 - use ranges to map foreman ranges

Instead of using 'range' setting I would propose to introduce a setting ('free_ip_address_allocation'  perhaps?) to select ip address allocation strategy (not sure about the names): 
 - 'use_whole_network'
 - 'use_foreman_ranges'

**Comment by witlessbird** [comment]
I'm going to close this ticket --  the questions in it have been resolved.
